base: ghcr.io/vanilla-os/core:main
name: Vanillin OS
singlelayer: false
labels:
  maintainer: Maksym Hazevych <mhazevych@proton.me>
args:
  DEBIAN_FRONTEND: noninteractive
runs:
  - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
modules:
  - name: vanilla-tools
    type: shell
    source:
      type: tar
      # switch to production build once in production
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
    commands:
      - mkdir -p /usr/bin
      - cp /sources/vanilla-tools/lpkg /usr/bin/lpkg
      - cp /sources/vanilla-tools/cur-gpu /usr/bin/cur-gpu
      - chmod +x /usr/bin/lpkg
      - chmod +x /usr/bin/cur-gpu
